
// import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Providers from "./providers";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // regular → bold
});


export const metadata = {
  title: "My Namaz | Krishnagiri",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
   
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={poppins.className}
      >
        <Providers >
        {children}
        <footer className=" text-black text-center">
          <Footer />
        </footer>
        </Providers>
      </body>
    </html>
  );
}
